a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
c=int(input("enter the third number:"))
largest = max(a, b, c)
smallest = min(a, b, c)
print("The largest number is:", largest)
print("The smallest number is:", smallest)
